name: GitHub Action
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push
    branches: release
jobs:
  Build-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event$
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server host$
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your rep$
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned t$
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner$
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
